#![allow(dead_code)]
[package]
name = "fiberslice-5d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_grid = "0.1.0"
egui_extras = "0.21.0"
bevy = "0.10.1"
bevy_egui = "0.20"
smooth-bevy-cameras = "0.8.0"
winit = "0.28.6"
image = "0.24.6"