#![allow(dead_code)]
[package]
name = "fiberslice-5d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_grid = "0.2.0"
egui_extras = "0.22.0"
strum = "0.25.0"
strum_macros = "0.25.0"
image = { version = "0.24.6" }
lazy_static = "1.4.0"
macros = { path = "macros" }
traits = { path = "traits" }
thiserror = "1.0.30"
serde = "1.0.177"
serde_yaml = "0.9.25"
stl_io = "0.7.0"
nfde = "0.0.8"
uni-path = "1.51.1"
phf = { version = "0.11", features = ["macros"] }
winit = "0.28.6"
three-d = { version = "0.16.3", features = ["egui-gui"] }
three-d-asset = "0.6.0"
tokio = { version = "1.34.0", features = ["macros", "full"] }
serde_json = "1.0.64"
parking_lot = "0.12.1"
egui_glow = "0.22.0"
glow = "0.12"
