#![allow(dead_code)]
[package]
name = "fiberslice-5d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_grid = "0.1.0"
eframe = "0.21.3"
egui_wgpu_backend = "0.23.0"
egui_extras = "0.21.0"
egui = "0.21.0"
egui_demo_lib = "0.21.0"
egui_glow = "0.21.0"
egui_web = "0.17.0"
bevy = "0.10"
bevy_egui = "0.20"