#![allow(dead_code)]
[package]
name = "fiberslice-5d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

egui = "0.22.0"
egui_grid = "0.2.0"
egui_extras = "0.22.0"
winit = "0.28.6"
strum = "0.25.0"
strum_macros = "0.25.0"
image = { version = "0.24.6" }
lazy_static = "1.4.0"
macros = { path = "macros" }
traits = { path = "traits" }
thiserror = "1.0.30"
serde = "1.0.177"
serde_yaml = "0.9.25"
stl_io = "0.7.0"
nfde = "0.0.8"
bevy = { version = "0.11.2", features = ["dynamic_linking", "wayland"] }
bevy_egui = { git = "https://github.com/mvlabat/bevy_egui" }
bevy_atmosphere = { git = "https://github.com/JonahPlusPlus/bevy_atmosphere" }
bevy_obj = "0.11"
uni-path = "1.51.1"
phf = { version = "0.11", features = ["macros"] }
futures-lite = "2.0.0"
bevy_mod_picking = "0.16.0"
approx = "0.5.1"
rand = "0.8.5"
three-d = { git = "https://github.com/asny/three-d.git", features = [
    "egui-gui",
] }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
