#![allow(dead_code)]
[package]
name = "fiberslice-5d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_grid = "0.1.0"
egui_extras = "0.21.0"
bevy = "0.10.1"
bevy_egui = "0.20"
smooth-bevy-cameras = "0.8.0"
bevy_atmosphere = "0.6.0"
bevy_stl = "0.8.0"
strum = "0.24.1"
strum_macros = "0.24.3"