#![allow(dead_code)]
[package]
name = "fiberslice-5d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_grid = "0.1.0"
egui_extras = "0.21.0"
winit = "0.28"
web-sys = "0.3"
wasm-bindgen = "0.2"
strum = "0.25.0"
strum_macros = "0.25.0"
image = { version = "0.24.6" }
lazy_static = "1.4.0"
macros = { path = "macros" }
traits = { path = "traits" }
three-d = { git = "https://github.com/asny/three-d.git", features = [
    "egui-gui",
    "serde",
] }
thiserror = "1.0.30"
three-d-asset = { git = "https://github.com/asny/three-d-asset", features = [
    "gltf",
    "serde",
    "image",
    "obj",
] }
tokio = { version = "1.29.1", features = ["macros", "full"] }
serde = "1.0.177"
serde_yaml = "0.9.25"
