name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install libasound2
        run: sudo apt install libasound2-dev
      - name: Install libudev-dev
        run: sudo apt install libudev-dev
      - name: Install pkg-config
        run: sudo apt install pkg-config
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
